producto_index:
    path:     /
    defaults: { _controller: "ProveedorBundle:Producto:index" }
    methods:  GET

producto_show:
    path:     /{idproducto}/show
    defaults: { _controller: "ProveedorBundle:Producto:show" }
    methods:  GET

producto_new:
    path:     /new
    defaults: { _controller: "ProveedorBundle:Producto:new" }
    methods:  [GET, POST]

producto_edit:
    path:     /{idproducto}/edit
    defaults: { _controller: "ProveedorBundle:Producto:edit" }
    methods:  [GET, POST]

producto_delete:
    path:     /{idproducto}/delete
    defaults: { _controller: "ProveedorBundle:Producto:delete" }
    methods:  DELETE
