proveedor_index:
    path:     /
    defaults: { _controller: "ProveedorBundle:Proveedor:index" }
    methods:  GET

proveedor_show:
    path:     /{idproveedor}/show
    defaults: { _controller: "ProveedorBundle:Proveedor:show" }
    methods:  GET

proveedor_new:
    path:     /new
    defaults: { _controller: "ProveedorBundle:Proveedor:new" }
    methods:  [GET, POST]

proveedor_edit:
    path:     /{idproveedor}/edit
    defaults: { _controller: "ProveedorBundle:Proveedor:edit" }
    methods:  [GET, POST]

proveedor_delete:
    path:     /{idproveedor}/delete
    defaults: { _controller: "ProveedorBundle:Proveedor:delete" }
    methods:  DELETE
