XYZ\ProveedorBundle\Entity\Producto:
    type: entity
    table: producto
    id:
        idproducto:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        productonombre:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
            column: productoNombre
        productoprecio:
            type: float
            nullable: false
            precision: 10
            scale: 0
            column: productoPrecio
    lifecycleCallbacks: {  }
